### ISSUE TITLE
te propongo esto

### ISSUE THREAD

**Issue by JLVegeta** [bucanero/apollo-ps3#1]
para hacerlo aun mas definitivo, permiteme darte unos consejos para añadir:

una opcion de copiar partida desde el mismo programa, tanto de consola a pendrive, como de pendrive a consola, y al mismo tiempo que se copia se parcheen y reasignen directamente, eso estaria realmente genial y lo convertria en definitivo, para los que como yo tenemos dos PS3 podriamos usar nuestras partidas en ambas consolas de forma rapida y facil, sin tener que ir partida por partida parcheando, reasignando y luego copiar desde el menu de la consola, nos ahorrariamos todo eso, por ejemplo unas opcion que digna:
parchear todas las partidas (y nosotros escogemos que parchea,r claro esta), reasignar todas las partidas, copiar todas las partidas a (y ya escogemos si pendrive o consola), con esas tres opciones ademas de las que ya tiene ahora seria fantastico, eso si, tambien se pudieran esas tres opciones a partidas individualmente, no se si me explico.

un saludo y muchas gracias por esta gran utilidad.

**Comment by bucanero** [comment]
copiar de HDD a USB es algo simple, se reduce a transferir los archivos y no deberia dar problemas

el caso inverso (copiar de USB a HDD), no es tan simple, porque es necesario actualizar la base de datos interna del XMB para que la partida "aparezca" en el menu XMB luego de copiarla.
Si solo se transfieren los archivos, la PS3 no verá el save-game y será necesario hacer un "rebuild database" desde el recovery menu para que la consola detecte la partida guardada.

Tengo algunas ideas que probar para "actualizar" la base de datos interna del XMB, pero tengo que hacer pruebas primero y ver los resultados.

del manejo "bulk" de partidas, es una posibilidad pero primero tengo otras prioridades (eliminar bugs) y funcionalidades que quiero pulir y agregar.

**Comment by bucanero** [comment]
Bulk save-game resign added in 5f32dfcf658852b0cde23b6d27603c8490ecfceb

**Comment by bucanero** [comment]
- `Copy savegame to HDD` option added in d718c5baac92bc7f99fc4bc05d108011d8027e4f
- Bulk copy USB to HDD option added in a1136e964082b2edaf5442a8c1d7d53b378963fa

**Comment by bucanero** [comment]
[v1.2.5](https://github.com/bucanero/apollo-ps3/releases/tag/v1.2.5) released
