### ISSUE TITLE
Detail freezes.

### ISSUE THREAD

**Issue by delanolima** [bucanero/apollo-ps3#10]
The “Details” option freezes if there is no save file in the USB device.

**Comment by bucanero** [comment]
Yes, I've been notified of this bug.

**Comment by bucanero** [comment]
Fixed in https://github.com/bucanero/apollo-ps3/commit/1dcca3c32080308166c4a2afe3b108c3ec2110d4

**Comment by retrosapien** [comment]
I'm not sure if this is the same bug, but even on current version when I press triangle (details?) in most screens it either does nothing or causes a freeze. (Need to hard reset, or use webman mod webserver /shutdown command) 
Webman mod shutdown button combo is non responsive. 
Using PS3HEN 3.0.2 on HFW 4.86

I've actually never seen the details button work as expected.

**Comment by bucanero** [comment]
> I'm not sure if this is the same bug, but even on current version when I press triangle (details?) in most screens it either does nothing or causes a freeze. (Need to hard reset, or use webman mod webserver /shutdown command)
> Webman mod shutdown button combo is non responsive.
> Using PS3HEN 3.0.2 on HFW 4.86
> 
> I've actually never seen the details button work as expected.

hard to guess where are you selecting "details", so you need to provide more information
for example, "details" on a cheat code will show the actual patch code, but on a save-game it will show the file path and owner information.

Open Apollo, go to `settings`, and click on "enable debug log". After enabling logs, try to use Apollo and select the detail option is some items.
If it gets stuck again, get the log file from `/dev_hdd0/tmp/apollo.log` and send it over so I can review the issue.

**Comment by retrosapien** [comment]
I just noticed the function of the triangle button changes on some pages. I think it was actually the 'view code' function that froze the ps3. I will try your suggestion. I just noticed the new version, so i will update an see if i can reproduce the same results and get back to you with the log file.
I'm still figuring things out with this app and all the different ps2 saves and card extensions. not to mention the different ways to launch a ps2 game. Its confusing, to say the least.

**Comment by retrosapien** [comment]
I tried for about 10 minutes to try to crash the old version before updating, and i couldn't do it. 
It could have had something to do with my usb drive. 
I couldn't remember the condition of the OP. So tried without usb, as well. when i get time i will check with a usb with out save files.
Or maybe enabling the log fixed it. 
;-)
