### ISSUE TITLE
Corrupted on install

### ISSUE THREAD

**Issue by DeadParticles** [bucanero/apollo-ps3#100]
whenever i try to install a version of Apollo it always ends up corrupted
![Screenshot 2022-11-30 16-35-27](https://user-images.githubusercontent.com/25615468/204913092-c47927b8-ad79-4d6f-9270-97cc2758f509.png)

**Comment by bucanero** [comment]
Can't help, that's an issue on your system. All the releases have been tested and work fine for any CFW or HEN user.

**Comment by DeadParticles** [comment]
> Can't help, that's an issue on your system. All the releases have been tested and work fine for any CFW or HEN user. (4.84+)

im not really sure what to do or why it is doing this

**Comment by bucanero** [comment]
> > Can't help, that's an issue on your system. All the releases have been tested and work fine for any CFW or HEN user. (4.84+)
> 
> im not really sure what to do or why it is doing this

I'd suggest asking on PS3 forums or sites like reddit.com , where other users might give you ideas to test your system.

**Comment by DeadParticles** [comment]
> > > Can't help, that's an issue on your system. All the releases have been tested and work fine for any CFW or HEN user. (4.84+)
> > 
> > 
> > im not really sure what to do or why it is doing this
> 
> I'd suggest asking on PS3 forums or sites like reddit.com , where other users might give you ideas to test your system.

ok well thanks for the info
