### ISSUE TITLE
Restaurar trofeos

### ISSUE THREAD

**Issue by Nacheras** [bucanero/apollo-ps3#102]
Hola! 
He hecho una copia de seguridad de mis trofeos en formato .zip, pero ahora no encuentro como poder restaurarlos de nuevo a la consola, se deben copiar manualmente con multiman o el programa trae la opción escondida en algún otro sitio?

Gracias y felices fiestas

**Comment by bucanero** [comment]
Por el momento lamentablemente Apollo no incluye la opcion de restaurar el backup de trofeos. La unica alternativa es hacerlo manualmente.

Asumiendo que sigue siendo la misma PS3, con la misma cuenta y usuario, se puede hacer:
- descomprimir los .zip
- copiar los archivos a la PS3 (por USB o FTP)
- darle a la opcion de "rebuild database" de la PS3 para que vuelva a detectar todos los trofeos copiados

nota: si se ha cambiado de consola ,cuenta o usuario, habria que usar Apollo para resignar los trofeos antes del rebuild

**Comment by bucanero** [comment]
duplicate #74

**Comment by Nacheras** [comment]
Perfecto, muchísimas gracias, sigue siendo la misma consola y la misma cuenta, así que no debería resignar nada.

**Comment by bucanero** [comment]
Menu para importar trofeos agregado: 3141a95a2099b5a6798a6e1914910903df879dd2

**Comment by Nacheras** [comment]
Perfecto, lo probaré, al final lo hice manualmente como me dijiste y funcionó sin problemas.

**Comment by bucanero** [comment]
> Perfecto, lo probaré, al final lo hice manualmente como me dijiste y funcionó sin problemas.

El cambio estará disponible en la proxima version, pero si quieres hacer "beta testing" antes del release, puedo enviarte un `.pkg` de prueba.

**Comment by Nacheras** [comment]
> > Perfecto, lo probaré, al final lo hice manualmente como me dijiste y funcionó sin problemas.
> 
> El cambio estará disponible en la proxima version, pero si quieres hacer "beta testing" antes del release, puedo enviarte un `.pkg` de prueba.

Perfecto, como tú estimes, no tengo problema en probarlo y comentarte que tal funciona 👍

**Comment by bucanero** [comment]
> Perfecto, como tú estimes, no tengo problema en probarlo y comentarte que tal funciona 👍

La version 1.8.0 ya está disponible, si puedes probar lo de importar algun trofeo, sería bueno para confirmar tus resultados que coincidan 👍
