### ISSUE TITLE
Final Fantasy XIII cheats not working and loading modified save

### ISSUE THREAD

**Issue by whitezombie2000** [bucanero/apollo-ps3#108]
I've used Jappi88's FFXIII Encryption tool with BSD in the past to edit saves without issue. I decided to try this tool today but I am not having success adding cheats. I backed up my save like I always do when modifying,  I launch the tool, I go to HDD Saves, choose my FFXIII save I want to edit, and choose the cheat from the list I want to use like Potions. Update APP.DAT Checksum (Required), Encrypt APP.DAT (Required), Decrypt APP.DAT (Required), are auto selected when choosing a cheat, then I select Apply Changes & Resign, and I get a message "save MRTC00003 successfully modified". I exit the app, launch the game, choose the modified save, and it just kicks me back to the title screen. I cannot get the modified save to load with this tool.

**Comment by bucanero** [comment]
I checked on my side, and I have introduced a bug in the latest version regarding the FF13 decryption.

Right now, I suggest trying the previous version 1.7.4, which should work fine since it was before the ff13 encryption bug.

**Comment by bucanero** [comment]
Fixed in v1.8.4
