### ISSUE TITLE
Dark Souls - Duplicate savegame slot 1 in slot 2

### ISSUE THREAD

**Issue by JLCaballeroMQ** [bucanero/apollo-ps3#113]
I have a game / character in slot 1 of the savegame, and before starting ng+ I would like to duplicate slot 1 in slot 2. How can I do it?
Thank you.

**Comment by bucanero** [comment]
This is a game specific question, you should ask on forums like [psx-place.com](http://psx-place.com) in case some ps3 players know how to do it.
