### ISSUE TITLE
Feedback a bug

### ISSUE THREAD

**Issue by gfhhhg** [bucanero/apollo-ps3#114]
A bug in the feedback games.conf file

; "Ninja Gaiden Sigma" (Thanks to aerosoul94)[BLUS30051/BLUS30036/NPUB30851/NPUB90017/BLES00072/NPEB90008/BCAS20040/BCAS20012/BLAS50160/BCKS10013/BCKS10040/BLJM55046/BLJS10005/BLJS50003]; disc_ hash_ key=secure_ file_ id:*=5113A25B77940C01C1BD993AC1BD993A;  "Ninja Gaiden Sigma 2"[BLUS30380/BLUS30440/NPUB30852/NPUB90274/BLES00736/NPEB01257/BLJM60168/NPJB00258/NPJB90207/BLAS50160/BLAS50144/BLKS20170/BLJM55022/BLAS50357/NPHB00159]; disc_ hash_ key=secure_ file_ id:*=0F1F2F3F4F5F6F7F8F9FAFBFCFDFEFFF

BLAS50160 is incorrect in Ninja Gaiden Sigma, which can cause damage to the BLAS50160 archive of Ninja Gaiden Sigma2

**Comment by bucanero** [comment]
Fixed in https://github.com/bucanero/apollo-patches/commit/fde6e5ac9cda2a66f6d150f22b8c879ef61b50c3
