### ISSUE TITLE
Load 

### ISSUE THREAD

**Issue by SpicyWheatPeppers** [bucanero/apollo-ps3#116]
![image](https://user-images.githubusercontent.com/131197855/232870644-7cf44a05-6948-47ce-9ae8-6ecd606d0aa6.jpg)
It just does this infinitely everything else works I even 100% deleted everything and reinstalled and that did nothing. Any help?

**Comment by bucanero** [comment]
you probably have junk data under the `home/user/savedata` folder. Test on a clean ps3 setup, with a new clean user.

**Comment by SpicyWheatPeppers** [comment]
@bucanero how can I clean it on my main user
