### ISSUE TITLE
Device activation error in 1.8.4

### ISSUE THREAD

**Issue by Laz221** [bucanero/apollo-ps3#120]
I recently got a super slim (4.90 HEN). I'm on an offline account and when I tried to activate the device it gave "account id is not valid" error. I tried activating on psn but it also gave an error. I had to revert to 1.7.0 and the activation feature worked like a charm.

**Comment by DrearyBear** [comment]
My device activation was fine, then I caused this error by manually deleting my /dev_hdd0/home/00000001/exdata/act.dat and act.bak files and trying to activate again in Apollo Save Tool.

I found reverting 1.8.0 to work as well.

**Comment by bucanero** [comment]
You'll get the `account id is not valid` error if Apollo already detected an account ID for the current user, or if the account ID you enter on the on-screen keyboard is invalid. If the user-id was already linked at some point, data on xRegistry.sys remains and Apollo will detect it and avoid further changes.

It's not an error, as Apollo is trying to avoid issues if someone tries to activate the same user account many times with different account IDs. Saves and trophies are linked to that account data and everything could become corrupt and lost if something like that happens.

The best and safe way is to create a new user, and then activate it. A new clean user won't have any old linked data and will avoid any data corruption.

**Comment by bucanero** [comment]
fixed in d8177864cbd7456a1a4d57bf7d2327cdf2a9c55a
