### ISSUE TITLE
Turning off cheats part of saves

### ISSUE THREAD

**Issue by kiasilverfatalis** [bucanero/apollo-ps3#123]
Not really an issue. But is it possible, when examining them in the cfw? I'm playing final fantasy x-2 hd remaster, and want to turn off all party members level 99. So I can do creature creator

**Comment by Masamune3210** [comment]
If you saved after having the cheat enabled, you are going to have to use a save editor to modify the levels or start over with a new save. Things like this is why its said to not save after enabling cheats.

**Comment by kiasilverfatalis** [comment]
Thank you for getting back to me, I figured I'd just start a new game, and
activate the cheats that way, on the save. My bad, I JUST discovered the
awesome tool. I was wondering, how do I make them constantly work, without
having to quit and activate the cheats again?
