### ISSUE TITLE
Apollo improperly adds "System" attribute to exported files when copying to USB

### ISSUE THREAD

**Issue by DeepMac** [bucanero/apollo-ps3#125]
Discovered copying some files from a PS3 to USB, using Apollo, will improperly add the "System" attribute to the files. Examples:

- Trophies
- RAP files
- idps.hex
- act.dat

On Windows computers, the System attribute is a legacy bit set that will hide the file from view in Windows explorer, and will return "file not found" errors when attempting to interact with the files in a CMD or Powershell interface. Only if a user has explicitly enabled the options in Windows Explorer to show Hidden AND System files will they be visible and copyable.

**Comment by bucanero** [comment]
Right, I haven't used Windows in ages so I missed this one. 

A good thing would be to get a complete list of all the exported USB files that could get this `system` attribute so when I work on a fix I don't miss some edge case.

**Comment by DeepMac** [comment]
Can confirm it did it for all the file types listed in the original report. I'll test ZIP files. I don't think it did it for saves but I'll double-check.
Probably you just want to always make sure the bitmask for the FAT32 attribs never has System set, because it's definitely never going to be needed or justifiable for this application.

**Comment by DeepMac** [comment]
Can confirm it adds system attribute to ZIP files, along with the TXT and XML files created exporting to ZIP (for HDD Save Games)

![image](https://github.com/bucanero/apollo-ps3/assets/4560942/5a0d3eda-3648-4de8-b534-23bc0e0fa586)

**Comment by DeepMac** [comment]
Forgot to add to original report, this was on the latest release, v1.8.4 on a PS3 slim

**Comment by bucanero** [comment]
> Can confirm it adds system attribute to ZIP files, along with the TXT and XML files created exporting to ZIP (for HDD Save Games)
> 

thanks for providing all the details and testing all the different export files. I'll get this fixed in the next release. I might ping for testing as I don't have a Windows pc around and a virtual machine might not provide the best results.

**Comment by DeepMac** [comment]
No worries, I'll keep my PS3 handy for now.

**Comment by bucanero** [comment]
what version of windows are you using that showed this System attribute? I'm currently testing on Windows 7, I also have a Win10 virtual machine but I wonder if you're using some older version like win XP and maybe newer version don't care about that S flag.

**Comment by DeepMac** [comment]
I use Windows 10, specifically: Microsoft Windows [Version 10.0.19044.3086]

It's a file-system attribute that is supported on FAT and NTFS systems. If you have a new version you want me to test for you happy to help, I'll have some free time this week.

**Comment by bucanero** [comment]
@DeepMac , can you try this Apollo build? https://www.mediafire.com/file/gwrz09ol62tw94w/apollo-ps3.pkg/file

I have fixed the FAT32 attribute and on my tests (with Windows 7) all files are ok. (tested with saves, trophies, .Zips, .raps, `idps.hex`, saves from online DB)

Having an additional test and confirmation with your PS3 and your Windows PC would be very helpful. 
Let me know if everything works or if you find any case where the `S` attribute is still tagged on the USB file.

**Comment by bucanero** [comment]
fixed in 1648b4a74ff05c5bdf32b205785372c258684205

**Comment by DeepMac** [comment]
> @DeepMac , can you try this Apollo build? https://www.mediafire.com/file/gwrz09ol62tw94w/apollo-ps3.pkg/file

Tested, works like a champ. I do miss the doggos in the splash screen tho...

> I have fixed the FAT32 attribute and on my tests (with Windows 7) all files are ok. (tested with saves, trophies, .Zips, .raps, `idps.hex`, saves from online DB)

Confirmed here too. All attribs look fine.

**Comment by bucanero** [comment]
> > @DeepMac , can you try this Apollo build? https://www.mediafire.com/file/gwrz09ol62tw94w/apollo-ps3.pkg/file
> 
> Tested, works like a champ. I do miss the doggos in the splash screen tho...
> 

Thanks for testing, the fix will be in the new 1.8.6 version 👍 

About my dogs, they're still in the app. 🐶  I made a little easter egg for them. Just open the "About" menu, and then press `SELECT`. A picture of them, and a short message will show up. (then you can press `Circle` to go back to the main menu)
