### ISSUE TITLE
Decrypt save file operation completes but does not create a .DAT file

### ISSUE THREAD

**Issue by DeepMac** [bucanero/apollo-ps3#129]
V1.8.4 on a PS3 Slim with HEN v3.1.1

I was able to decrypt all of my save games using Apollo except two.  For Borderlands, I could decrypt the main profile save file (PAYLOAD.DAT). But for the actual character save game, while Apollo reported it decrypted the file to the hard drive, there was no file there.

I loaded the save game into Borderlands on my PS3 no problem and resaved the game. Repeated the attempt, same failure. I also deleted the empty directory on the PS3 HDD and tried again. It creates the directory, but writes no file to it.
I assume the decryption operation is failing but not giving an error for some reason. 

I found one other game where there was no file created, Ultraton.

**Comment by DeepMac** [comment]
Screenshots, for clarity.

![x (2)](https://github.com/bucanero/apollo-ps3/assets/4560942/2c641869-6529-4a14-9f81-563ff5c9adbb)
![x (3)](https://github.com/bucanero/apollo-ps3/assets/4560942/918433aa-2479-4f15-9bf9-ebd156f71295)
![x (1)](https://github.com/bucanero/apollo-ps3/assets/4560942/a69f20b3-e029-458b-9a93-cb63efb9a181)

**Comment by bucanero** [comment]
can you upload the Borderlands save that is not exporting decrypted data?

you can use Apollo to "export save as .ZIP" and then just upload the zip here.

**Comment by DeepMac** [comment]
Hmmm, github claims it can't handle a ZIP file even though it says it can. I just love opening more cases to fix a case to fix a bug, >_<

**Comment by DeepMac** [comment]
[example.zip](https://github.com/bucanero/apollo-ps3/files/12841648/example.zip)

Nevermind, browser issue on my end. See attached. No shaming my terrible progress, 😆

**Comment by bucanero** [comment]
I was checking the provided save, and actually `SAVE0001.SAV` is not encrypted . (seems that Borderlands is one of the few games that doesn't use the secure-key encryption)

So I assume Apollo detects is not encrypted, doesn't decrypt the file and that's why ends up saying "decrypted ok" but no file is copied to `tmp/apollo`.
I need to either improve the message on screen, or just copy the file anyways even if it's not encrypted. (instead of decryption it would be just a regular file copy)

**Comment by DeepMac** [comment]
If the file isn't encrypted than I feel the proper action would be to copy the original file. The copying should be a separate step after decryption process, in other words. Only if there's an error returned by decrypting or attempting to load the save should it not copy and of course that'd be a different error message.
So good to know that, but sad because the save doesn't load in Borderlands as-is. I assumed because it was decrypted. Sooo something else is going on I guess, :(
