### ISSUE TITLE
build issue: freetype/config/ftheader.h: No such file or directory

### ISSUE THREAD

**Issue by lmirel** [bucanero/apollo-ps3#13]
on Ubuntu 18.04 I get:
In file included from /mnt/PS3/dev/proj/apollo-ps3/source/ttf_fonts.c:1:0:
/usr/local/ps3dev/portlibs/ppu/include/ft2build.h:56:10: fatal error: freetype/config/ftheader.h: No such file or directory
 #include <freetype/config/ftheader.h>

**Comment by lmirel** [comment]
in ps3dev/portlibs/ppu/include/ft2build.h it states:
/* `<prefix>/include/freetype2' must be in your current inclusion path */
so I added the following into the Makefile under export INCLUDE:
-I$(PS3DEV)/portlibs/ppu/include/freetype2

**Comment by bucanero** [comment]
I think this really depends on how you have setup your dev-environment and toolchain.
In my case, all the stuff in `./portlibs/ppu/include/` is included already

btw, I'm using this version of the FreeType lib:
https://github.com/ps3dev/ps3libraries/blob/master/scripts/004-freetype-2.4.3.sh

**Comment by bucanero** [comment]
Just for reference, after installing my toolchain in macOS, I have a link between `./freetype/ -> ./freetype2/freetype/` , so perhaps the linux toolchain is not keeping that symlink.
