### ISSUE TITLE
Can't transfer Condemned 2 save from BLES to BLUS. 

### ISSUE THREAD

**Issue by gir489returns** [bucanero/apollo-ps3#135]
I'm trying to get the only 100% save file for Condemned 2 posted online working on my BLUS copy of Condemned 2. I put the BLES00219_LIST-CHKPT folder into PS3/SAVEDATA on my USB drive and Apollo sees it, and I told it to do a Change Region operation from BLES00219 to BLUS30115 and Update ADD for FILENAME.SAV. I then click Apply changes and resign, it takes about a minute, and then it says it's done. I tell it to copy the file to the HDD, which it says it did. I can see that a save called BLES00219_LIST-CHKPT is now in my save folder with the subtitle Saved by Apollo Save Tool. I then go to play Condemned, but it thinks I'm on Level 1 with no upgrades. If I click continue, it loads me to where the save was, which is at the final boss, but I can't beat him because I don't have my Oro unlocks to stun him.

Am I doing something wrong? Included are the 100% save file and an export of a save file I made by starting the game and saving immediately.

[BLES00219_LIST-CHKPT.zip](https://github.com/bucanero/apollo-ps3/files/13470187/BLES00219_LIST-CHKPT.zip)
[BLUS30115-00000001.zip](https://github.com/bucanero/apollo-ps3/files/13470189/BLUS30115-00000001.zip)

**Comment by bucanero** [comment]
changing regions is not bullet-proof, games might have slightly different save-data between regions, so files don't match the data the game is expecting.
The game loaded the save so Apollo did the resigning Ok. If you want, you can also try changing regions using a PC tool like "Bruteforce savedata" and compare results.

Also, if you want to see why some items are not available you'll have to manually compare save data files between regions.

**Comment by gir489returns** [comment]
Thanks for your response @bucanero. You made me realize I was barking up the wrong tree, as you mentioned, it was clearly working. There are actually 2 save files the game generates, a profile save, and a checkpoint save. While I had the checkpoint save, I was missing the profile save. I have generated the profile save, and now everything is unlocked. Thanks for your time and effort.

**Comment by bucanero** [comment]
good to hear that the resigning + region change by Apollo worked fine. 

It's true that many games have that structure, they keep some information on a "profile" save and another chunk of data on the "auto-save/checkpoint" save.

Btw, I've just merged the save you sent to `apollo-saves` 👍
