### ISSUE TITLE
a option to copy trophies between users

### ISSUE THREAD

**Issue by br0moment0** [bucanero/apollo-ps3#14]
it would be nice to have a option to get trophies from an old account to a newer one just by copying them but I think that needs resigning just like saves so I thought that it would be cool that Apollo could do that since it can copy trophies to usb

**Comment by bucanero** [comment]
yes, trophies require resigning or else they'll end up corrupting everything

I still have many things to add/fix for PS3 saves, so trophies are not a priority right now. Also it would require a lot of testing to avoid complaints from users if their trophy account gets corrupted.

**Comment by bucanero** [comment]
trophy resign has been added in 767817ebcba0edf6323358904e690842bfaa7d91

trophy backup (copy to USB) was already available, so now with the resign feature you could actually restore a trophy set from an old account.

**Comment by bucanero** [comment]
a complete Trophy edit, resign & unlock feature was added in https://github.com/bucanero/apollo-ps3/commit/45e7657affd7697c05492896d78cf8f87dc2e989
