### ISSUE TITLE
unlock all the storage trophies on the ps3 at one time(I mean bulk trophies)we have to unlock one by one game trophy

### ISSUE THREAD

**Issue by Gituser1098** [bucanero/apollo-ps3#140]
pls bucanero, make this possible C:

**Comment by bucanero** [comment]
if you want to mass-unlock trophies , I suggest trying the trophy plugin that actually unlocks everything in a single step.

Try google or youtube and you'll find this plugin and how to use it.

**Comment by Gituser1098** [comment]
What is the name of the plugin? I can find a plugin but it needs to unlock entering game per game

**Comment by bucanero** [comment]
Yes, but that's the plugin I was talking about. You still need to start each game to unlock.

**Comment by Gituser1098** [comment]
Mm thats the thing,is so boring unlocking one by one
Thats the why i think you can,with your apollo

**Comment by Gituser1098** [comment]
@bucanero 
The PS3 community would appreciate it if you could make that Bulk option

**Comment by bucanero** [comment]
I'm not planning working on trophies, but any other developer is free to work on it and submit a pull request.
