### ISSUE TITLE
Feature request: Sync via LAN

### ISSUE THREAD

**Issue by NiQ1** [bucanero/apollo-ps3#152]
I have two PS3s in my house (living room and bedroom). It would be really nice if we could sync saves directly between them via LAN (maybe also add an option to manually enter IP address for those who use VPNs).

There is a separate utility that allows uploading saves to Google Drives but it hasn't been maintained for quite a while now, people are reporting issues, and besides, it would be nice to have an option that does not rely on a cloud service.

**Comment by bucanero** [comment]
you could set the IP address of the other ps3 for the online DB URL, under the "Settings" option. That way one ps3 might be able to browse the content from the other system. Then you click "Online DB" and PS3-A should show stuff from PS3-B.

assume PS3-A IP = 192.168.1.11
PS3-B IP = 192.168.1.22

on PS3A settings you enter the custom Online DB URL = `http://192.168.1.22/`

test it out, I don't have two systems around to test but in theory it could work.
