### ISSUE TITLE
Apollo Does Not Resign NCAA14 Roster Save File

### ISSUE THREAD

**Issue by WilletsM4** [bucanero/apollo-ps3#153]
Although Apollo shows that I am the owner of the save file as I resigned it, whenever I open NCAA14 and try to load my roster file, it states "an error has occurred. (80120003) The file was created by another user and cannot be loaded.

**Comment by bucanero** [comment]
Games can have additional security checks that are custom and not managed by Apollo.

You can test, keep the original save on USB, resign it with Apollo and use the XMB to copy the save to HDD. If the save was not resigned properly the XMB will report that the save is not from the user. If it gets copied ok then the standard layer was resigned Ok and anything else is part of a custom game check.
