### ISSUE TITLE
v2.0.0 crashing on startup

### ISSUE THREAD

**Issue by gut5** [bucanero/apollo-ps3#157]
rebug 4.86
webman-mod 1.47.46

PS3 crashes and forces a system check (requires a controller to be connected and then does a HDD check) when attempting to run apollo-ps3.

**Comment by gut5** [comment]
restored ps3 filesystem/rebuild db, appears to be working now.

**Comment by HQSantosilva** [comment]
@gut5 I'm still having this issue, but i've just made the jailbreak of my ps3 today, could you help me out on the stuff i could do to fix this issue?

**Comment by gut5** [comment]
> @gut5 I'm still having this issue, but i've just made the jailbreak of my ps3 today, could you help me out on the stuff i could do to fix this issue?

I posted the solution in that comment
