### ISSUE TITLE
Please fix black screen issue on Rebug 4.84 Rex Edition and up

### ISSUE THREAD

**Issue by KrazyDragon777** [bucanero/apollo-ps3#16]
The application keeps showing a black screen after the bucanero logo shows up. I can here the music but that is all there is. I am on Rebug 4.84 Rex Edition. I haven't tested it but this also might be an issue with later firmwares. Please fix this.

**Comment by bucanero** [comment]
I've no reports of issues while running Apollo on CFWs.
have you tried other Apollo versions? e.g. v0.65 , v0.91 or v1.00 ? is your PS3 connected to the network?

since the app starts properly, I assume there's an issue somewhere else.
