### ISSUE TITLE
Error! USR-DATA couldn't be decrypted (X) OK

### ISSUE THREAD

**Issue by jlnhlfan** [bucanero/apollo-ps3#162]
![image](https://github.com/user-attachments/assets/97333066-ecc4-4b63-aa25-6ed6c5a12a39)

I received this error message upon attempting to decrypt a roster file for NHL 2K7 for use in RPCS3 because my PS3 tends to get kind of hot when I play it.

Is there anything I am doing wrong, or is the error expected for this particular game?

**Comment by bucanero** [comment]
maybe the secure-key for that game is missing, you should enable the application logs from `Settings` to get more details.

**Comment by jlnhlfan** [comment]
[apollo.log](https://github.com/user-attachments/files/17671162/apollo.log)
Here's the log.

**Comment by jlnhlfan** [comment]
Looks like they're already useable in RPCS3.
