### ISSUE TITLE
save hack loops while modify batman origins

### ISSUE THREAD

**Issue by Darkcast** [bucanero/apollo-ps3#17]
I new to this tool so I am not sure if this is normal but. I tried to mofify the save for a game I have in an external hard drive when I try to modify the save file it asks me that I have to do required task to complete the save hack but when I do it get stock in a loop or somethin 
i left it for 1 hour and it was still running the logo loading. 

Require:
Decompress Save
Compress Save
Update CRC32Big for SPBATAMAN 

my ps3 set up
PS3 CFW Rebug 4.84.2 CEX
Apollo Save Tool 1.02
Game Batman Origins BLUS31207 (brazil)

**Comment by bucanero** [comment]
Support for compressed save-games added in https://github.com/bucanero/apollo-ps3/commit/033b9127d2420cdf5d0d871951e26dd9f6b85e16

Feature will be available in the next release.

**Comment by bucanero** [comment]
Available in [v1.0.9](https://github.com/bucanero/apollo-ps3/releases/tag/v1.0.9)
