### ISSUE TITLE
Loading save games... Long time... 

### ISSUE THREAD

**Issue by lsfrc** [bucanero/apollo-ps3#18]
Hi there thank you for your app! Would like to ask why im stucked in Loading Save Games... to enter in online db. Im waiting for 15mins. Is this normal?

Thanks!

**Comment by bucanero** [comment]
no, it's not normal, the application had a problem. It looks like your PS3 is not connected to the web, or at least Apollo can't reach the URL to fetch the online DB data.

A quick check you can do, is to try loading this URL from your PS3:
http://apollo-db.psdev.tk/PS3/games.txt

if you can't load that page from the ps3, then the online DB won't work.

**Comment by lsfrc** [comment]
Thank you for the reply. No I dont have any connection problem. Im runing 4.85hen. The data base dont have GTAV save game so no problem I will do it by hand. Thanks!
