### ISSUE TITLE
savedata region change feature

### ISSUE THREAD

**Issue by naru232** [bucanero/apollo-ps3#19]
Hello bucanero i am writing to request a good idea on a future feature that you can add into apollo, usually on bruteforce there is an option that allows to you to change the savedata region or title ID to any ID that you may require, it works on many games, so far in most games that i test that are around more than 100 games works fine, also that includes the most PS3 famous games that most of the players may have, have a nice day

**Comment by bucanero** [comment]
could you help testing this feature? 
I probably can add it, but don't have the time or the different games to check if it actually works (e.g. changing a `BLUSxxxx` save to `BLESxxxx`)

so I need some testers to validate the "region change" before I release it

**Comment by naru232** [comment]
sure actually i have been testing this feature for some time ago and actually it works fine, if you like i will 2 savedatas that actually both belong to the same tpe of data but on different game type of region, thanks a lot so actually i do it from bruteforce

**Comment by naru232** [comment]
actually i will leave the links that actually you will be able to download the 2 savedatas, the one from BCES00065 belongs to the original file from uncharted and the one from BCUS98103 is the savedata that i changed the save region on it, also in order to work once i change region i reassign the save on this case by using apollo and works for me afther the region change of the savedata actually both belong to uncharted

https://mega.nz/file/zgtmkKDa#IWcgkUh_gF-uNPX49SXDNEg7kQtmOjYbM8ngzY-Au5s- this is the link from the BCES00065 savedata

https://mega.nz/file/K0tQwQaQ#ItVgidWTQ1nKtJ-JRVSOlPXJi-KAGCxGW_Jg8EBX3oA- this is the link from the modified BCUS98103 savedata

**Comment by bucanero** [comment]
great, thanks for the information. 👍 

I'll share an EBOOT.BIN to test the feature when ready, so you can actually try using Apollo to change the region+resign and see if it works properly with the Uncharted game.

**Comment by naru232** [comment]
sure no problem thanks bucanero i will do my best as well

**Comment by bucanero** [comment]
Change region implemented in: 121c678b166b34d4833260e97a83cb32c3d409bb

@naru232 , could you try the EBOOT.BIN from this zip: [apollo.zip](https://github.com/bucanero/apollo-ps3/files/4894082/apollo.zip) ?

If you can, on USB open one of those saves (BCES00065) and then try the option "Change region Title ID". It should show all the supported title IDs, like BCUS98103. You select the region you want, and then you need to click on "Apply changes & resign".
If everything worked ok, on the USB drive you'll have a save with the new region ready to use.

let me know if it works ok!

**Comment by naru232** [comment]
and bucanero sorry where could i put this eboot.bin maybe on the save itself? or which will be the location of it?

**Comment by naru232** [comment]
i was trying to place in the eboot.bin file but then it does not identify any changes about region save so far

**Comment by bucanero** [comment]
> and bucanero sorry where could i put this eboot.bin maybe on the save itself? or which will be the location of it?

you need to replace the EBOOT.BIN in this folder:
`/dev_hdd0/game/NP0APOLLO/USRDIR/`

once you replace the `EBOOT.BIN`, you launch Apollo, and open one of the USB saves. You should see a new option `Change region Title ID`

**Comment by naru232** [comment]
hello bucanero i test this feature, there is a thing here, i wanted to ask if tis possible to enable the option to manually type the region desired to have changed, it is because that when i try ti change region on the savedata only shows to me the same region of the save instead of showing me other options, about the change the screen shows that was successful, still it will be good to enable the manual typing of the region just in case, i will leave a photo that shows that i mean, best regards

**Comment by naru232** [comment]
https://mega.nz/file/mg8BSRgI#0R2V1dce8W0PSbfSS41BPTETNMnVBBJmkiTzJYAyU0U- here is the link about the photograph i hope that it can be seen jaja and also helps you a lot have a nice day

**Comment by bucanero** [comment]
thanks for the information @naru232 . I see the issue, actually Uncharted 1 is one of the few games that are not listed in the `games.conf` file, so Apollo doesn't have information to show other available TITLE_IDs.

I'm not going to add the "manual title edit" right now, because I still need to work on other stuff and handling the on-screen keyboard would take some time.

Can you try with any other game? it should show more title_id options for most of the savegames.

If you still want to try with Uncharted, you'll need to edit the `games.conf` file in the `/dev_hdd0/game/NP0APOLLO/USRDIR/DATA/` folder, adding the title_ids:

```
; "Uncharted"
[BCUS98103/BCES00065/SOME00ID/OTHER00ID]
```

**Comment by naru232** [comment]
ohh i see thanks bucanero i managed to edit the region, it is showing me right now the corrct regions to change and then it works fine

**Comment by bucanero** [comment]
Region change option added in 121c678b166b34d4833260e97a83cb32c3d409bb

**Comment by bucanero** [comment]
Fixed in [v1.2.0](https://github.com/bucanero/apollo-ps3/releases/tag/v1.2.0) . 
Please test the new version, it should support Uncharted 1 too. (it was added to the db)

**Comment by ShyavanS** [comment]
I was trying to use the region change feature for the sly collection (getting my physical game saves to work with the digital version from PSN) and it only gives the digital version for sly 1 which is only one game in the collection? Is there a way to manually add a title ID to make it change to the other two? (Physical for North America is BCUS98246 and it only shows digital North America as the one for Sly 1; NPUA80663, Sly 2 and Sly 3, the other two games in the collection are NPUA80664 and NPUA80665 respectively.)
