### ISSUE TITLE
Support for The Saboteur

### ISSUE THREAD

**Issue by Invictaz** [bucanero/apollo-ps3#2]
The game The Saboteur uses a notoriously hard to crack PFD. 
After resigning it shows corrupt with Aldo's Tools Bruteforce Savedata.
I hope you can fix it in this new homebrew.

**Comment by bucanero** [comment]
I don't know that game and I've no idea about the details, but the .pfd encryption and format is standard for every game and is handled by the PS3 system (games can't even read/write the SFO/PFD files)

if you're resigning a valid game file from another user, it should not show as corrupt.
but if you're applying cheats and patches, then that's a different thing. Cheats are modifying the data files and they could break the validation.

As a test, if you have a valid "the saboteur" save file, just copy it to USB, and try to resign it with Apollo. Then browse the USB saves from the XMB and see if it shows as valid or corrupt.

**Comment by Invictaz** [comment]
It does show as valid, no cheats were used. The game sees it as invalid. 
There were rumors of double encryption on EA games. Not sure.

**Comment by bucanero** [comment]
ok, I see; if the XMB browser shows it as valid, then the .PFD resigning was done properly, and the save passes the PS3 validations.
My guess is that the issue is in the game itself. The developers probably added some other check or internal validation, and they can see that the save was not created on that console/user. Unless someone debugs the game and reverse-engineer those checks, I think it won't work.

**Comment by Invictaz** [comment]
@bucanero Could you please check it? Maybe it works for you and I did something wrong. Better safe than sorry. Maybe I slipped up.

**Comment by bucanero** [comment]
sorry I don't have that game, I can't check it

**Comment by Invictaz** [comment]
@bucanero I can supply you with an ISO if you like

**Comment by Invictaz** [comment]
@bucanero I supplied you the eboot.elf decrypted on Twitter, please check.

**Comment by bucanero** [comment]
Sorry but I don't have time for such analysis. Try asking on some PS3 forums
