### ISSUE TITLE
some possible enhancements

### ISSUE THREAD

**Issue by mohasi** [bucanero/apollo-ps3#21]
I used apollo for the first time recently, there are a couple of things I feel could be improved:

1. The GUI could resize to fit my 1080p screen, there are black bars. I see options to adjust but they can never get rid of the bars completely and its something that really should not need adjustment.

2. Many of the options were self explanatory, but "Remove Account" and "Remove Console" I did not know what they are used for, I feel there should be some sort of hint text that should explain when and why these are useful. If not in the app itself then on github instead.

3. The recalc hash options should not be selected unless something else is selected which requires them.

**Comment by bucanero** [comment]
thanks for the feedback

> 1. The GUI could resize to fit my 1080p screen, there are black bars. I see options to adjust but they can never get rid of the bars completely and its something that really should not need adjustment.

have you changed the vertical/horizontal values in the `Settings` menu?
For example, using +30 vertical, +30 horizontal, do you still see black bars? You could go up to +100 for each. In my screen, when using +20 the screen is already fully covered by the background image.

> 3. The recalc hash options should not be selected unless something else is selected which requires them.

yes, I'll keep this in mind for the next version.

**Comment by bucanero** [comment]
issue 3 has been addressed in f491bb2e164a315bc570b6ce331bb09c48cc093a
