### ISSUE TITLE
Local backup (HDD to HDD)

### ISSUE THREAD

**Issue by marysiamzawka** [bucanero/apollo-ps3#22]
This is a thing I expected this tool to do out of the box.

Being able to make a local copy of a savefile would be useful in a case where your game has only one save slot, and would also eliminate a need for a USB drive (good for setups with all USB slots taken, like mine *wink wink*)

**Comment by bucanero** [comment]
a copy from HDD to HDD would mean that the save is "hidden" from the XMB, but if it's just for backup then it's still useful

I think I can just add an option to "export as .zip" and save a backup to the HDD (`/dev_hdd0/tmp/` maybe?)

**Comment by marysiamzawka** [comment]
yeah that would do the trick

perhaps also being able to change the directory's name for easier management

**Comment by bucanero** [comment]
Added `Zip savegame to HDD` option in d718c5baac92bc7f99fc4bc05d108011d8027e4f

**Comment by bucanero** [comment]
[v1.2.5](https://github.com/bucanero/apollo-ps3/releases/tag/v1.2.5) released
