### ISSUE TITLE
MINECRAFT

### ISSUE THREAD

**Issue by rambooo9000** [bucanero/apollo-ps3#39]
APOLLO  MİNECRAFT PLAYSTAİON EDİTON NPEB01899 LVL 255 TTURN WOODEN PİCKAXE TO DİAMOND HAS NOT BEEN İN CREATİVE   
WHICH VERSION DO THESE CHEATS WORK ON?   1.00 NOT WORKING

**Comment by bucanero** [comment]
This patch for Minecraft requires #38 . It should work in a next release of Apollo when the feature is added.

**Comment by bucanero** [comment]
I added the things missing for this minecraft cheat in ec68b9c264d35cfbe475d80ea0b8d62ccab8aa02: 
- support for variables across patches,
- `search next` command support  

but I don't own the game so I can't confirm this cheat actually works.
