### ISSUE TITLE
Copying trophies takes hours to complete

### ISSUE THREAD

**Issue by retrosapien** [bucanero/apollo-ps3#42]
[Edit] it finally finished, still have to check tomorrow if the trophies copied to the USB. In my excitement, I accidentally pressed the triangle button, which seems to have no other purpose than to freeze my ps3. I used the webserver to shutdown before going to bed. 

Apollo has been "copying trophies" for over an hour. 

Actually I'm not sure what it is doing. I can still press the home button and access the xmb, so it's not a complete freeze. 

I can also still ftp to and from the ps3 using webman mod in the background. I can't find anything on USB or HDD that indicates Apollo is actually copying anything. 

PS3HEN 3.0.2 CECH-3001B HFW 4.86

Also, side note. Is it possible to convert  from an opl bin containing multiple saves to a VME that can be used on ps2classics placeholder on PS3HEN with only this app?

**Comment by bucanero** [comment]
yes, I'm aware that copying files to USB is quite slow, the code needs optimization there to improve the transfer rates. Doing a bulk transfer of all trophies can take a while, as each trophy folder has many files too.

If speed is an issue, I suggest to avoid bulk copy of trophies or saves, unless you really have no other choice. For mass copy & speed, currently using a file manager like IRISMAN will offer a much better result.

btw, if you're using Apollo v1.5.0, you can avoid the Trophy bulk copy and just backup the ones you want. Also if you select "export trophy to Zip" that should be faster as it only writes a single file to USB.

**Comment by retrosapien** [comment]
I just seen that option in the new version. 
I was wondering what "vase" would sit there. 
I will definitely consider that for future backups.
=)
