### ISSUE TITLE
Encrypt PFD Save files 

### ISSUE THREAD

**Issue by JJ3647** [bucanero/apollo-ps3#50]
Can you add Encrypt PFD Save files option? I do hex editing to my save games.

**Comment by bucanero** [comment]
you can already do it with Apollo v1.5.0:

- select a save-game
- click "Decrypt save-game file"
- decrypt a file from the list
- manually hex-edit the decrypted file in `/tmp/apollo/BLUSxxxxx/`

once the decrypted file is modified:
- select the save-game
- click "Import save-game file"
- select the modified file from the list
- click "Apply changes & resign"

that way you can do manual hex-editing to any file, and import it back to the save-game.

**Comment by JJ3647** [comment]
Thank you, I'll take a look later.
