### ISSUE TITLE
Importing *.rap Files Fails Successfully

### ISSUE THREAD

**Issue by SephirothFan** [bucanero/apollo-ps3#52]
To Whom This May Concern,

I am attempting to import *.rap files from USB 0, but every time I try I get this message: "Files successfully copied to: /dev_hdd0/home/00000001/exdata/, but when I confirm the import, the files aren't there and there is no exdata directory.  I've tried creating a new exdata directory and applying permissions in the mmCM File Manager, but nothing seems to be working.

Is this a bug or am I doing something wrong?

I am using a CECHA01 PlayStation 3 with REBUG 4.84.2 DEX Custom Firmware installed and I have confirmed that the files have *.rap extensions, NOT *.RAP extensions.

Thanks for your help!
ZXRyuu

**Comment by bucanero** [comment]
`.rap` activation only works if the user account has been activated. (log in with an account, then activate the console for games)

if you don't have a folder `/dev_hdd0/home/00000001/exdata/`, then it means the user has not activated the console. Apollo can't activate consoles, so the license activation will fail. If the account is activated, you should see a file `/dev_hdd0/home/00000001/exdata/act.dat`

I guess I need to add a verification for `act.dat` and change the notification message.

**Comment by SephirothFan** [comment]
Okay, thanks for the response!  I will go down the route of activating my console and try this again.
