### ISSUE TITLE
Unlocking tropies over a recently-formatted PS3 not working (error 80022D11)

### ISSUE THREAD

**Issue by IlDucci** [bucanero/apollo-ps3#55]
Greetings, I'm having a bit of a situation after replacing my HDD in a PS2 Slim.

So I had an old backup from an old console of mine (I swapped a FAT with my current Slim), and I used my keys to unlock the backup, get all the data, copy it to my new HDD, then resign the saved games (they seem to work correctly, haven't tested them all)... and then I went to the trophies.

I've tried using both Bruteforce and your tool to resign them, but with no avail: all the games that contain trophies kick me out of the game with the 80022D11 error. By taking a look at the current ID, it seems to be a blank value. I haven't connected this PS3 after the formatting because it has a CFW, so maybe the ID's gone because it has not connected to PSN? 

With the latest version I also tried to do the database rebuild after resigning, but the results are equally negative. Could you please help me out?

**Comment by bucanero** [comment]
I guess that without ps3 activation, the old trophies won't work, even if you resign them.
Apollo and Bruteforce savedata use the same tools under the hood, so if you didn't get it working with BSD, Apollo won't solve it either.

btw, if you connect and activate, if you have sync'ed trophies with your old PS3, you can just let the ps3 sync and restore all the trophies from the online servers.

**Comment by IlDucci** [comment]
> btw, if you connect and activate, if you have sync'ed trophies with your old PS3, you can just let the ps3 sync and restore all the trophies from the online servers.

If I connect and activate, I risk a ban I do not want to affect my newer consoles. The only thing I could think of right now is that some of the games I have no trophies unlocked, so I got a copy of the old trophy files and the new ones generated with this console. Would you be willing to take a look at those files and see what changes could be done?

The other solution, I guess, would be reformatting the HDD, reinstalling the firmware twice and then hack the console back, right?

**Comment by bucanero** [comment]
you can install latest OFW, activate and then jailbreak it again
or you can try using a dual-boot firmware (it's the same as OFW but should let you reinstall CFW)

once your ps3 is activated with the same account, you should be able to sync trophies and then go back to CFW

**Comment by jhonathanc** [comment]
I think I found a solution @bucanero

Both TROPUSR.DAT and TROPTRNS.DAT has account_id inside. PS3TrophyIsGood don't change it inside theses files (only on PARAM.SFO). Probably updating it to the right information could work.

I also think this is the problem why copies from a console to another was not working on our tests...

**Comment by bucanero** [comment]
> I think I found a solution @bucanero
> 
> Edit.: Nvm, I just saw you already did it in the right way... So, there is nothing to do about account_id. Sorry :(.

yes, I was about to say that Apollo is already updating the `account-id` on those files. 
We still have some unknown hashes in those TROPxxx.DAT files, so my guess is that those hashes could be linked to the account and/or console, and since we can't re-calculate them, the files fail the verification process.

There's some information about trophy hashes on the ps3 dev wiki, but it's not complete. The only real way would be to decompile and reverse the original ps3 code and see how it really works.
