### ISSUE TITLE
[Feature Request] Add option to ignore and delete backup (_BU_) trophy sets.

### ISSUE THREAD

**Issue by ghost** [bucanero/apollo-ps3#64]
Backup Trophy Sets: https://psdevwiki.com/ps3/Trophy_files#Trophy_Installer

If there exists a backup trophy set in the console, Apollo will appear to list the trophy set for a game twice, and only through careful observation can one determine which one is the trophy set that's in use (that is, if the user knows about these _BU_ sets, otherwise there'll be confusion as to which is the one they should edit/use). It would be more convenient to label these sets as "Backups/Old_Trophies" and give the option to ignore and/or delete them from the console since they aren't necessary to use trophies. 

Though, I guess to avoid confusion, it would be best to hide them by default, give the option to optionally show them with a label in the trophy list, and add an option to delete them entirely (I don't know if deleting them will cause problems with PSN syncing, this would be more of an option for new games which have been updated but never used).

P.S. I wonder, if one imports a trophy set from another user, and then installs a newer trophy set from an update, would PSN syncing work? If true, would it be possible to create packages with the same version of the trophies and "update" the patched ones to sync properly? I guess it would be something to look into.

**Comment by bucanero** [comment]
Backup `_BU_` folders are now skipped from the trophy list. (3e6016f)
