### ISSUE TITLE
Not unlocking platinum?

### ISSUE THREAD

**Issue by ghost** [bucanero/apollo-ps3#66]
I was trying to unlock a platinum, but no matter what I did it wouldn't show/unlock the trophy. It said I had 100% completed, but the platinum wasn't unlocked. This was the first time I have had this happen to me. Also did A rebuild database. Anyone tried this to?

**Game:** South Park - Stick of Truth

**Comment by Maocorre** [comment]
Deberías revisar el programa ya hice lo que recomiendas incluso dejando un trofeo fácil y los platino simplemente quedan bloqueados lo hice en dos juegos y ahora no se que más para corregirlo

**Comment by bucanero** [comment]
If you have issues, use the [trophy unlocker plugin](https://github.com/bucanero/apollo-ps3/files/7403190/trophy.unlocker.zip)

**Comment by Maocorre** [comment]
Pude corregir trofeos que fueron cargados al psn

**Comment by Maocorre** [comment]
Una pregunta si se cambia la fecha de un trofeo a una fecha antes del trofeos que está registrado ya en psn este puede ser cambiado
