### ISSUE TITLE
100% but platnuim still locked 

### ISSUE THREAD

**Issue by Rage4Dayz96** [bucanero/apollo-ps3#70]
I got most of the trophies legit, only used your tool to get the speedrun trophy and all collectible trophy and went and did the last trophy in-game but the plat didn't unlock so I used your tool to unlock it, and now when I'm in "Online Mode" it says 100% but the platinum is still locked but in offline mode, it's unlocked. Not sure how to fix it. 
Also, I'm running the latest HEN
Thank you (
![Screenshot_20211016-195509_PS App](https://user-images.githubusercontent.com/82603863/138553939-a0837e7d-b372-4cd7-a92b-6b1123121b17.jpg)
:

**Comment by Rage4Dayz96** [comment]
> You can check the workaround mentioned here: [#66 (comment)](https://github.com/bucanero/apollo-ps3/issues/66#issuecomment-947911404)
> 
> basically: you need to remove the trophy folder, start again, and then use the "trophy unlocker plugin" to unlock everything. When you sync, you'll only sync the last remaining trophy (platinum).

Thank you, it's now fixed.

**Comment by yuritoOW** [comment]
I'm having the exact issue with one of my games called: The Amazing Spider-Man, platinum is still locked but everything else is unlocked. I tried the workaround where you delete the trophy folder and use the trophy unlocker but the trophy unlocker wouldn't say its loaded when I press R1 and Circle. 

Unless I am somehow deleted the wrong folder then I dont know which one to delete.

Thank you

**Comment by fsvlad** [comment]
hi, i have the same problem. But i don't know how remove the trophy folder. Anyone can help plz ?

**Comment by x-magic** [comment]
> hi, i have the same problem. But i don't know how remove the trophy folder. Anyone can help plz ?

Use multiman to delete /dev_hdd0/home/<user>/trophy folder, use PS3 recovery menu to rebuild database to fully reset local trophies. Now you should see no games listed in trophies menu on XMB. Go through each game with the unlocker plugin to unlock all trophies including platinum, and finally sign in to PSN and sync trophies.
