### ISSUE TITLE
Possible bug: PSN Account ID not overwriting

### ISSUE THREAD

**Issue by gtessi** [bucanero/apollo-ps3#75]
Hi Buk, hope you are well.

I've cleaned up all of my PSN account data from `xRegistry.sys` and deleted my `act.dat` file in order to prepare everything for a new PSN account without the need to wipe out my HDD.

After I've logged into PSN and activated my system with the new account, I went to Apollo Save Tool to resign all my savefiles but discovered that the stored account was the old one. So, I went to **Settings -> Update Account & Console IDs** so Apollo updates itself with the new `act.dat` information but no changes were applied: the old ID was not replaced.

The only workaround I've found was to delete Apollo's save file and run it again, letting it automatically find and store the new ID as usual. After that, everything worked as always and I could resign my savefiles.

Is this the expected behaviour?, or the logic implemented doesn't support/consider changing PSN accounts?.

Thank you for your time and for your contributions to the scene.

Cheers!.

**Comment by bucanero** [comment]
Hello,
mmm that's an edge case that I'm not sure if I have ever tested.... 🤔  I think that running the "update account" option from the `Settings` menu should have update every value, but maybe I missed something

I'll take a look when I have a chance, but I'm working on new homebrew projects right now so this might remain an open issue.
In any case, the workaround of removing the Apollo settings save file always fixes these kind of issues.

thanks for reporting!

**Comment by gtessi** [comment]
Don't worry Buk, I know that it is a very edge case and that you are working with other things.

In the end I could apply a workaround so no issues at all.

Thanks you.

Cheers!
