### ISSUE TITLE
Save encrypter/decrypter/checksum fix for Metal Gear Solid 5 TPP

### ISSUE THREAD

**Issue by khen90** [bucanero/apollo-ps3#76]
@bucanero 

Hi, is there any plans for developing save game tools for MGSV TPP PS3/PS4 as in the case of PS3 when i decrypt the save, apply cheats and then encrypt it back using Bruteforce returns error when loading the save in game. i don't know much about this but i came across a thread on reddit saying that it has something to do with like Blowfish software and/or that the save has additional encryption layer.

Lastly the Save Wizard team and someone from X360 scene cracked the save file on PS4 and x360 respectively.

Thanks.

**Comment by bucanero** [comment]
Metal Gear Solid 5 save-games have a custom encryption layer. It has been reversed for some platforms (like PC or Xbox I think) but not for the PS3 or PS4 (as far as I know).

Yes, the SaveWizard tool might have cracked it but that information is not public or shared, so it remains private. If someone wants to reverse and crack the ps3/ps4 encryption and share the info, then great, I can add it later to Apollo. If not, I won't be able to support that game.

**Comment by khen90** [comment]
Ok i understand, but there's a Japanese site which hosted Bruteforce savepatch like code and I'm leaving here with a link to it

https://emu.web-g-p.com/info/bbs/patchcode/ps3/bbs.cgi?list=pickup&num=2416

Think you can do something of it? I'm going to close the issue and thanks again.
Staysafe.

**Comment by khen90** [comment]
Hi again, I'm leaving the Japanese save editor online link to you and a save game to you. Hope you can manage to figure something out. 

https://emu.web-g-p.com/info/system/save_ps3_editor.html
[MGSV High level unities save 1.0.zip](https://github.com/bucanero/apollo-ps3/files/7924835/MGSV.High.level.unities.save.1.0.zip)

Thanks.
