### ISSUE TITLE
Last of use not working

### ISSUE THREAD

**Issue by deadpahn** [bucanero/apollo-ps3#79]
Hello,

Upgraded the harddrive today. When I put my last of us saves into the save data folder they don't appear. I used the bulk management to unlock the saves but it won't detect. Is there s special thing I have to do for TLOU? Thanks.

BONUS: If there was a way to make the game start from a certain point in the story, basically all I want.

**Comment by bucanero** [comment]
You need to copy the saves from USB to the console using the XMB menus. That's the right way to import a save.
