### ISSUE TITLE
[NPJB00785] Dengeki Bunko: Fighting Climax Ignition couldn't be resigned

### ISSUE THREAD

**Issue by V-Gamer-EX** [bucanero/apollo-ps3#83]
I tried to resign a complete save file on DB:FCI but it always failed with a resigned error. Fix?

**Comment by V-Gamer-EX** [comment]
Late reply but I dumped the secure_file_id key for it, so how can I edit it in the games.conf file?

**Comment by bucanero** [comment]
check the details on #27 , you'll need to copy, edit, and replace the games.conf file on the PS3.

Also, please share the `secure_file_id` for this title and I'll add it to the official database and will be available on the next update.

**Comment by V-Gamer-EX** [comment]
Here's the key:

; "Dengeki Bunko Fighting Climax Ignition"
[NPJB00785]
;disc_hash_key=
secure_file_id:*=4672656E636842726561640000000000

**Comment by bucanero** [comment]
Thanks 👍  I have added the key for this title.

You can download the updated games.conf here: https://github.com/bucanero/apollo-ps3/blob/master/appdata/games.conf and then replace the older file on your PS3 Apollo folder.
