### ISSUE TITLE
error al intentar eliminar trofeo

### ISSUE THREAD

**Issue by apostador455** [bucanero/apollo-ps3#86]
llevo dias tractando de eliminar los trofeo de un juego y no puedo y apollo no tiene la opcion de eliminar trofeos para areglar un platino ojala tuviera la opcion de eliminar trofeo es delas mejores aplicacion la uso demasiado

**Comment by bucanero** [comment]
keep in mind, if the trophy has been synced then it cannot be deleted, the data is already on the trophy servers.

if the trophies are not synced, then you can use Apollo to "lock" the trophy again. Just select and apply changes. Then you'll need to rebuild the DB.
