### ISSUE TITLE
Apollo on RPCS3

### ISSUE THREAD

**Issue by mitch03** [bucanero/apollo-ps3#87]
I love Apollo, but wanted to ask if there was a chance that maybe in the future support could be added for trophies for RPCS3, as it loads on RPCS3 but wont let me unlock trophies on it, thankyou!

**Comment by bucanero** [comment]
The problem is that the emulator is not using the correct and original file format for the trophies. It's not really an issue with Apollo. I don't have time to work on emulator support, and also my app is meant to be used on real PS3 hardware.

**Comment by mitch03** [comment]
@bucanero hey, is it possible to change the region of game save on RPCS3 with apollo, as i tried to change the last of us EU to US region but doesnt seem to work, thanks in advance

**Comment by bucanero** [comment]
I'm not supporting emulators so I don't really know. If it doesn't work, then you might want to do it manually with some windows PC tools.

**Comment by mitch03** [comment]
do you know which tools i would need? like what to download?

**Comment by bucanero** [comment]
you could try "Bruteforce save data" tool (could be other tools but I don't really know). Check on forums or reddit
