### ISSUE TITLE
Save decrypt option

### ISSUE THREAD

**Issue by LittleStinky123** [bucanero/apollo-ps3#9]
It would be really useful to store a save in a decrypted form on a USB drive.
The aldostools bruteforce save data isn't open source and offered on mostly not trustworthy sites, so I would really like to see this option added to apollo.
With rpcs3 improving constantly, moving the own collection of saves to it would be really nice.

**Comment by bucanero** [comment]
yes, Bruteforce is not open source, but actually the decryption in Bruteforce data is done by flatz's PFD tools, and it's executed as a background helper tool.

flatz's PFD tools are open source, you can find the code here:
https://github.com/bucanero/pfd_sfo_tools

In my repo I've shared a macOS binary version, but the code could be compiled on Windows and Linux without issues.

I'll keep the idea in mind for a future version, but meanwhile I suggest you just get pfd_tools so you can decrypt/encrypt/resign any save on your computer. Probably much easier if you're using the rpcs3 emu.

**Comment by bucanero** [comment]
`Save decrypted file` added in https://github.com/bucanero/apollo-ps3/commit/bfffc8841706b131152310e68cfa08d82793164e

it should be available in the next release.

**Comment by Melechtna** [comment]
> yes, Bruteforce is not open source, but actually the decryption in Bruteforce data is done by flatz's PFD tools, and it's executed as a background helper tool.
> 
> flatz's PFD tools are open source, you can find the code here: https://github.com/bucanero/pfd_sfo_tools
> 
> In my repo I've shared a macOS binary version, but the code could be compiled on Windows and Linux without issues.
> 
> I'll keep the idea in mind for a future version, but meanwhile I suggest you just get pfd_tools so you can decrypt/encrypt/resign any save directly on your computer. Probably much faster if you're using the rpcs3 emu.

Where did this go?
