### ISSUE TITLE
Terraria save files

### ISSUE THREAD

**Issue by minch-yoda** [bucanero/apollo-ps3#92]
Great tool, but failed on Terraria.

Steps:
Unencrypt and encrypt back any of the files, CONFIG.DAT, PLAYER1.PLR, WORLD0.WLD

Expected:
Since nothing changed should totally work

Result:
Terraria says "Save data is corrupt, rewrite save data?" etc.

**Comment by bucanero** [comment]
maybe the decryption key is wrong 

can you test with a working save, only click on "apply changes & resign", so the save gets resigned without changes to the files. If the save works after resign, then I'd suspect of the decryption key.

To validate the decryption key, using HEN or CFW, go to the HFW/CFW Tools menu on the XMB and select the option to dump Secure File IDs. Then open your game, and load a savegame. The decryption key will be dumped on a log file, check on /dev_hdd0/ for a log file and report the secure-id value.
