### ISSUE TITLE
KH 2.5 HD Saves untranferable

### ISSUE THREAD

**Issue by batsu2** [bucanero/apollo-ps3#93]
Had success with transferring all save files from one account on my slim ps3 to another account on the same ps3 (through copying from the HDD to a USB, then back to the HDD) except for all save files having to do with Kingdom Hearts 2.5 HD ReMix. Tried repeatedly to resign to the new account ID but it never worked, they were never recognized as being the new account's ownership. Had to scrap the files which was unfortunate since I lost about 10 hours or so of progress.

**Comment by bucanero** [comment]
If you were able to copy the resigned saves from USB to HDD using the XMB with the new account, then the standard PS3 ownership protection was properly resigned. (it's validated on XMB copy so if the save is invalid or if the hash doesn't match then the PS3 will not copy the save)

But games do have custom validations too, so if the save was rejected by the game (after a successful copy using XMB) then it's possible that a custom game check is in place. 

I'm not sure if you already erased the original save files, but I'd suggest to take the original untouched saves and try to resign them using the PC app "Bruteforce Save data" by aldostools. If resigning with that PC tool works, then there's a bug with Apollo. But if you get the same error, then it's a game custom integrity check.
